### PR TITLE
Tomo render page

### PR DESCRIPTION
**Pull request by sogimu**
Made integration with tomo raycaster 2. Solved problem with different ratio of datasets

### CODE REVIEW

**Comment by sogimu** [comment]
#matze, please, take look to this pull request

**Comment by sogimu** [comment]
@matze, please, take look to this pull request

**Comment by matze** [comment]
You introduced several problems that were fixed [already](https://github.com/ufo-kit/tofuweb/pull/5#issuecomment-119840585). Most importantly you should not use PIL to load TIFF files since you cannot be sure if the default file format is supported.

**Comment by matze** [comment]
:+1:

**Pull request merged**
