### PR TITLE
Intoducted raycasting tomo viewer

### PR DESCRIPTION
**Pull request by sogimu**

### CODE REVIEW

**Comment by sogimu** [comment]
Under score - Ok.
Name of process in Camel case.

```
RecoProcess
DownsizeProcess
MapProcess
```

Is it ok?

**Comment by matze** [comment]
Yes. When in doubt you should always refer to [PEP8](https://www.python.org/dev/peps/pep-0008/).

By the way, I think this single commit is not yet rebased against this master. As of now, I cannot merge it.

**Comment by matze** [comment]
Some outstanding issues: 
- [x] with Bower it should not be necessary to include jquery-ui.css and similar assets.
- [x] I don't see _all_ those icons used. If any are required, you could just use the ones we use from FontAwesome already.
- [x] At some places it looks like it was indented wrongly (manage.py and somewhere later).

**Comment by matze** [comment]
Two more things: 1) It's "Reconstruction" not "Reconstacion". 2) I get

```
Crashed slice map creation for reco.id=1. Error: cannot identify image file
```

How is this possible?

**Comment by sogimu** [comment]
Please, check the code

**Pull request merged**
